name: CI

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  build_extensions:
    runs-on: ${{ matrix.os }}
    if: false
    strategy:
      fail-fast: false
      matrix:
        example:
          - hello-world
          - toolbar-button
        os: [ubuntu-latest, macos-latest, windows-latest]

    defaults:
      run:
        working-directory: ${{ matrix.example }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Path filter
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            extension:
              - '${{ matrix.example }}/**'
      - name: Cache lerna
        if: steps.filter.outputs.extension == 'true'
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-lerna-
      - name: Check config files
        if: steps.filter.outputs.extension == 'true'
        run: |
          diff ../hello-world/tsconfig.json tsconfig.json
          diff ../hello-world/.eslintignore .eslintignore
          diff ../hello-world/.eslintrc.js .eslintrc.js
          diff ../hello-world/.gitignore .gitignore
          diff ../hello-world/ui-tests/playwright.config.ts ./ui-tests/playwright.config.ts
          diff ../hello-world/ui-tests/README.md ./ui-tests/README.md
        shell: bash
      - name: Install node
        if: steps.filter.outputs.extension == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install Python
        if: steps.filter.outputs.extension == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Get pip cache dir
        if: steps.filter.outputs.extension == 'true'
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache pip
        if: steps.filter.outputs.extension == 'true'
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install the Python dependencies
        if: steps.filter.outputs.extension == 'true'
        run: |
          python -m pip install --upgrade pip jupyter_packaging~=0.10 jupyterlab~=3.5.0
      - name: Install the NPM dependencies
        if: steps.filter.outputs.extension == 'true'
        run: jlpm
      - name: Lint the files
        if: steps.filter.outputs.extension == 'true'
        run: jlpm run eslint:check
      - name: Build and check by extension
        if: steps.filter.outputs.extension == 'true'
        run: |
          pip install . -v
          jupyter labextension list 2>&1 | tee labextension.list
          cat labextension.list | grep -ie "@jupyterlab-examples/*.*OK"
          python -m jupyterlab.browser_check
          pip uninstall -y $(python setup.py --name)
        shell: bash

      - name: Integration tests
        if: steps.filter.outputs.extension == 'true' && startsWith(runner.os, 'Linux')
        run: |
          docker-compose -f ../end-to-end-tests/docker-compose.yml --env-file ./ui-tests/.env down || true
          docker-compose -f ../end-to-end-tests/docker-compose.yml --env-file ./ui-tests/.env pull -q || true
          docker-compose -f ../end-to-end-tests/docker-compose.yml --env-file ./ui-tests/.env build
          docker-compose -f ../end-to-end-tests/docker-compose.yml --env-file ./ui-tests/.env run --rm e2e
      - name: Upload UI Test artifacts
        if: steps.filter.outputs.extension == 'true' && startsWith(runner.os, 'Linux') && always()
        uses: actions/upload-artifact@v3
        with:
          name: ui-test-output
          path: |
            ${{ matrix.example }}/ui-tests/test-results
      - name: Stop containers
        if: steps.filter.outputs.extension == 'true' && startsWith(runner.os, 'Linux') && always()
        run: |
          # Print jupyterlab logs before removing the containers using the container name set in docker-compose file
          docker logs jupyterlab
          docker-compose -f ../end-to-end-tests/docker-compose.yml --env-file ./ui-tests/.env down

  build_serverextension:
    runs-on: ${{ matrix.os }}
    if: false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Path filter
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            extension:
              - 'server-extension/**'
      - name: Cache lerna
        if: steps.filter.outputs.extension == 'true'
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('server-extension/package.json') }}
          restore-keys: |
            ${{ runner.os }}-lerna-
      - name: Install node
        if: steps.filter.outputs.extension == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Check config files
        if: steps.filter.outputs.extension == 'true'
        run: |
          diff hello-world/tsconfig.json server-extension/tsconfig.json
          diff hello-world/.eslintignore server-extension/.eslintignore
          diff hello-world/.eslintrc.js server-extension/.eslintrc.js
          diff hello-world/ui-tests/playwright.config.ts server-extension/ui-tests/playwright.config.ts
          diff hello-world/ui-tests/README.md server-extension/ui-tests/README.md
        shell: bash
      - name: Install Python
        if: steps.filter.outputs.extension == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Get pip cache dir
        if: steps.filter.outputs.extension == 'true'
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache pip
        if: steps.filter.outputs.extension == 'true'
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install the Python dependencies
        if: steps.filter.outputs.extension == 'true'
        run: |
          python -m pip install --upgrade pip jupyter_packaging~=0.10 jupyterlab~=3.1
      - name: Install the NPM dependencies
        if: steps.filter.outputs.extension == 'true'
        run: |
          cd server-extension
          jlpm
      - name: Lint the files
        if: steps.filter.outputs.extension == 'true'
        run: |
          cd server-extension
          jlpm run eslint:check
      - name: Build extension as user
        if: steps.filter.outputs.extension == 'true'
        # Force the usage of the source distribution (good practice)
        run: |
          cd server-extension
          python setup.py sdist
          pip install ./dist/jlab_ext_example* --pre --find-links=dist --no-cache-dir
          python -m jupyterlab.browser_check
      - name: Check extension as dev
        if: steps.filter.outputs.extension == 'true' && ( startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS') )
        run: |
          jupyter server extension list 2>&1 | tee serverextension.list
          cat serverextension.list | grep -ie "jlab_ext_example.*OK"
          jupyter labextension list 2>&1 | tee labextension.list
          cat labextension.list | grep -ie "@jupyterlab-examples/server-extension.*OK"
      - name: Clean extension installation
        if: steps.filter.outputs.extension == 'true'
        run: |
          pip uninstall -y jlab_ext_example
          jupyter lab clean
          jupyter server extension list
          jupyter labextension list
      - name: Build extension as dev
        if: steps.filter.outputs.extension == 'true'
        run: |
          cd server-extension
          pip install .
      - name: Check extension as dev
        if: steps.filter.outputs.extension == 'true' && ( startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS') )
        run: |
          jupyter server extension list 2>&1 | tee serverextension.list
          cat serverextension.list | grep -ie "jlab_ext_example.*OK"
          jupyter labextension list 2>&1 | tee labextension.list
          cat labextension.list | grep -ie "@jupyterlab-examples/server-extension.*OK"
          python -m jupyterlab.browser_check

      - name: Integration tests
        if: steps.filter.outputs.extension == 'true' && startsWith(runner.os, 'Linux')
        run: |
          cd server-extension
          docker-compose -f ../end-to-end-tests/docker-compose.yml --env-file ./ui-tests/.env down || true
          docker-compose -f ../end-to-end-tests/docker-compose.yml --env-file ./ui-tests/.env pull -q || true
          docker-compose -f ../end-to-end-tests/docker-compose.yml --env-file ./ui-tests/.env build
          docker-compose -f ../end-to-end-tests/docker-compose.yml --env-file ./ui-tests/.env run --rm e2e
      - name: Upload UI Test artifacts
        if: steps.filter.outputs.extension == 'true' && startsWith(runner.os, 'Linux') && always()
        uses: actions/upload-artifact@v3
        with:
          name: ui-test-output
          path: |
            server-extension/ui-tests/test-results
      - name: Stop containers
        if: steps.filter.outputs.extension == 'true' && startsWith(runner.os, 'Linux') && always()
        run: |
          cd server-extension
          # Print jupyterlab logs before removing the containers using the container name set in docker-compose file
          docker logs jupyterlab
          docker-compose -f ../end-to-end-tests/docker-compose.yml --env-file ./ui-tests/.env down

  build_all:
    runs-on: ${{ matrix.os }}
    if: false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache lerna
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-lerna-
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install the Python dependencies
        run: python -m pip install jupyter_packaging~=0.10 jupyterlab~=3.5.0 pytest pytest-check-links
      - name: Bootstrap the jlpm deps
        run: jlpm
      - name: Build all the extensions
        run: |
          jlpm lint:check
          jlpm build-ext
          jlpm install-ext
          # Check links as last step as new tutorial may set links not yet valid (like file not yet in master)
          pytest --check-links
